name: Build and test develop

on:
  push:
    branches: develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Dockerhub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build the image
        run: docker buildx build --push --tag danilsmirnov/postfix:${{ github.sha }} .

  test-ubuntu-22:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Run the image
        run: >
          docker run --name postfix -d -p 25:25
          -e MAIL_DOMAIN=example.com -e MAIL_HOST=mail.example.com -e SMTP_USER=user:pwd
          -e FAIL2BAN=enabled --cap-add NET_ADMIN
          danilsmirnov/postfix:${{ github.sha }}
      - name: Check the status
        run: |
          sleep 10
          status=$(docker exec postfix supervisorctl status)
          echo "$status" | grep -v RUNNING > /dev/null
          [ "$?" -eq 0 ] && { echo "$status"; exit 1; }
